New upstream version 1.27.90

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -356,6 +356,9 @@ shared_nm_std_aux_libnm_std_aux_la_SOURCES = \
 	shared/nm-std-aux/c-list-util.c \
 	shared/nm-std-aux/c-list-util.h \
 	shared/nm-std-aux/nm-dbus-compat.h \
+	shared/nm-std-aux/nm-std-aux.h \
+	shared/nm-std-aux/nm-std-utils.c \
+	shared/nm-std-aux/nm-std-utils.h \
 	shared/nm-std-aux/unaligned.h \
 	$(NULL)
 
@@ -636,6 +639,39 @@ shared_nm_glib_aux_tests_test_shared_general_LDADD = \
 	shared/libcsiphash.la \
 	$(GLIB_LIBS) \
 	$(NULL)
+
+###############################################################################
+
+if WITH_JANSSON
+
+check_programs += shared/nm-glib-aux/tests/test-json-aux
+
+shared_nm_glib_aux_tests_test_json_aux_CPPFLAGS = \
+	$(dflt_cppflags) \
+	-I$(srcdir)/shared \
+	-DNETWORKMANAGER_COMPILATION_TEST \
+	-DNETWORKMANAGER_COMPILATION='(NM_NETWORKMANAGER_COMPILATION_GLIB|NM_NETWORKMANAGER_COMPILATION_WITH_GLIB_I18N_PROG)' \
+	$(CODE_COVERAGE_CFLAGS) \
+	$(GLIB_CFLAGS) \
+	$(JANSSON_CFLAGS) \
+	$(SANITIZER_LIB_CFLAGS) \
+	$(NULL)
+
+shared_nm_glib_aux_tests_test_json_aux_LDFLAGS = \
+	$(CODE_COVERAGE_LDFLAGS) \
+	$(SANITIZER_EXEC_LDFLAGS) \
+	$(NULL)
+
+shared_nm_glib_aux_tests_test_json_aux_LDADD = \
+	$(JANSSON_LIBS) \
+	shared/nm-glib-aux/libnm-glib-aux.la \
+	shared/systemd/libnm-systemd-logging-stub.la \
+	shared/nm-std-aux/libnm-std-aux.la \
+	shared/libcsiphash.la \
+	$(GLIB_LIBS) \
+	$(NULL)
+
+endif
 
 ###############################################################################
 
@@ -1028,13 +1064,6 @@ libnm_core_lib_c_real = \
 	libnm-core/nm-vpn-plugin-info.c \
 	$(NULL)
 
-if WITH_JSON_VALIDATION
-libnm_core_lib_h_priv += \
-	libnm-core/nm-json.h
-libnm_core_lib_c_real += \
-	libnm-core/nm-json.c
-endif
-
 libnm_core_lib_c_mkenums = \
 	libnm-core/nm-core-enum-types.c
 
@@ -1088,11 +1117,6 @@ libnm_core_libnm_core_la_CPPFLAGS = \
 	-DG_LOG_DOMAIN=\""libnm"\" \
 	-DNETWORKMANAGER_COMPILATION=NM_NETWORKMANAGER_COMPILATION_LIBNM_CORE \
 	$(NULL)
-
-if WITH_JSON_VALIDATION
-libnm_core_libnm_core_la_CPPFLAGS += $(JANSSON_CFLAGS)
-libnm_core_libnm_core_la_CPPFLAGS += -fcommon
-endif
 
 libnm_core_libnm_core_la_SOURCES = \
 	$(libnm_core_lib_h_pub_real) \
@@ -2096,6 +2120,14 @@ src_libNetworkManagerBase_la_SOURCES = \
 	src/nm-dbus-utils.h \
 	src/nm-dbus-object.c \
 	src/nm-dbus-object.h \
+	src/nm-netns.c \
+	src/nm-netns.h \
+	src/nm-l3-config-data.c \
+	src/nm-l3-config-data.h \
+	src/nm-l3cfg.c \
+	src/nm-l3cfg.h \
+	src/nm-ip-config.c \
+	src/nm-ip-config.h \
 	src/nm-ip4-config.c \
 	src/nm-ip4-config.h \
 	src/nm-ip6-config.c \
@@ -2286,8 +2318,6 @@ src_libNetworkManager_la_SOURCES = \
 	src/nm-connectivity.h \
 	src/nm-dcb.c \
 	src/nm-dcb.h \
-	src/nm-netns.c \
-	src/nm-netns.h \
 	src/nm-dhcp-config.c \
 	src/nm-dhcp-config.h \
 	src/nm-dispatcher.c \
@@ -2440,7 +2470,9 @@ src_nm_iface_helper_LDADD = \
 	shared/nm-std-aux/libnm-std-aux.la \
 	src/libnm-systemd-core.la \
 	shared/systemd/libnm-systemd-shared.la \
+	shared/libnacd.la \
 	shared/libndhcp4.la \
+	shared/libcrbtree.la \
 	shared/libcsiphash.la \
 	$(GLIB_LIBS) \
 	$(LIBUDEV_LIBS) \
@@ -3094,6 +3126,7 @@ EXTRA_DIST += \
 	src/settings/plugins/ifcfg-rh/tests/network-scripts/ifcfg-Test_Write_Team_Infiniband_Port.cexpected \
 	src/settings/plugins/ifcfg-rh/tests/network-scripts/ifcfg-Test_Write_Team_Port.cexpected \
 	src/settings/plugins/ifcfg-rh/tests/network-scripts/ifcfg-Test_Write_VLAN_reorder_hdr.cexpected \
+	src/settings/plugins/ifcfg-rh/tests/network-scripts/ifcfg-Test_Write_WiFi_AP_Mode.cexpected \
 	src/settings/plugins/ifcfg-rh/tests/network-scripts/ifcfg-Test_Write_WiFi_Band_A.cexpected \
 	src/settings/plugins/ifcfg-rh/tests/network-scripts/ifcfg-Test_Write_WiFi_Hidden.cexpected \
 	src/settings/plugins/ifcfg-rh/tests/network-scripts/ifcfg-Test_Write_WiFi_MAC_always.cexpected \
@@ -4084,12 +4117,14 @@ src_tests_ldadd = \
 check_programs += \
 	src/tests/test-core \
 	src/tests/test-core-with-expect \
+	src/tests/test-dcb \
 	src/tests/test-ip4-config \
 	src/tests/test-ip6-config \
-	src/tests/test-dcb \
+	src/tests/test-l3cfg \
 	src/tests/test-systemd \
+	src/tests/test-utils \
 	src/tests/test-wired-defname \
-	src/tests/test-utils
+	$(NULL)
 
 src_tests_test_ip4_config_CPPFLAGS = $(src_cppflags_test)
 src_tests_test_ip4_config_LDFLAGS = $(src_tests_ldflags)
@@ -4119,13 +4154,18 @@ src_tests_test_utils_CPPFLAGS = $(src_cppflags_test)
 src_tests_test_utils_LDFLAGS = $(src_tests_ldflags)
 src_tests_test_utils_LDADD = $(src_tests_ldadd)
 
-$(src_tests_test_ip4_config_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
-$(src_tests_test_ip6_config_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
-$(src_tests_test_dcb_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
+src_tests_test_l3cfg_CPPFLAGS = $(src_cppflags_test)
+src_tests_test_l3cfg_LDFLAGS = $(src_devices_tests_ldflags)
+src_tests_test_l3cfg_LDADD = $(src_tests_ldadd)
+
 $(src_tests_test_core_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
 $(src_tests_test_core_with_expect_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
-$(src_tests_test_wired_defname_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
+$(src_tests_test_dcb_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
+$(src_tests_test_ip4_config_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
+$(src_tests_test_ip6_config_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
+$(src_tests_test_l3cfg_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
 $(src_tests_test_utils_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
+$(src_tests_test_wired_defname_OBJECTS): $(libnm_core_lib_h_pub_mkenums)
 
 src_tests_test_systemd_CPPFLAGS = \
 	$(src_libnm_systemd_core_la_cppflags) \
@@ -4850,6 +4890,8 @@ clients_cloud_setup_nm_cloud_setup_SOURCES = \
 	clients/cloud-setup/nmcs-provider-ec2.h \
 	clients/cloud-setup/nmcs-provider-gcp.c \
 	clients/cloud-setup/nmcs-provider-gcp.h \
+	clients/cloud-setup/nmcs-provider-azure.c \
+	clients/cloud-setup/nmcs-provider-azure.h \
 	$(NULL)
 
 clients_cloud_setup_nm_cloud_setup_CPPFLAGS = \
@@ -5257,6 +5299,26 @@ CLEANFILES += \
 ###############################################################################
 
 include Makefile.examples
+
+if WITH_PYTHON_BLACK
+check-python-black:
+	test "$$NMTST_SKIP_PYTHON_BLACK" != 1 && $(BLACK) --check $(top_srcdir) $(top_srcdir)/examples/python/gi/nm-wg-set
+check_local += check-python-black
+endif
+
+###############################################################################
+
+check-po-msgfmt:
+	@echo "check-po-msgfmt: check $(top_srcdir)/po/*.po files with msgfmt -vc"
+	@for f in "$(top_srcdir)/po"/*.po ; do \
+		if ! msgfmt -vc "$$f" -o /dev/null &>/dev/null ; then \
+			echo "invalid po file: msgfmt -vc $$f -o /dev/null" ; \
+			msgfmt -vc "$$f" -o /dev/null ; \
+			exit 1 ; \
+		fi ; \
+	done
+
+check_local += check-po-msgfmt
 
 ###############################################################################
 
